In [1]:
from pydataset import data
from scipy import stats
import env
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import acquire
import prepare
import warnings
from sklearn.metrics import confusion_matrix

# Exercise number 2

false positive would be a dog prediction and its an actual cat
false negative would be a cat prediction and its an actual dog

In [2]:
#model evaluation
(46 + 34) / (46 + 13 + 7 + 34)
#80% accuracy

0.8

In [3]:
46 / (46 + 13)
# 78% precision

0.7796610169491526

In [4]:
46 / (46 + 7)
#87% recall

0.8679245283018868

In [5]:
accuracy = pd.read_csv('accuracy_csv.csv')

In [6]:
accuracy

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [7]:
confusion_matrix(accuracy.actual, accuracy.model1)

# accuracy:
(8+182) / (8 + 8 + 2 + 182)
# 95%

0.95

In [8]:
confusion_matrix(accuracy.actual, accuracy.model2)
(9+103) / (9 + 7 + 81 + 103)
#56% accuracy

0.56

In [9]:
confusion_matrix(accuracy.actual, accuracy.model3)
(13+98) / (13 + 3 + 86 + 98)
#56% accuracy

0.555

#### the best outcome to measure for this issue would be accuracy. The most accurate model is model 1. 

In [10]:
# for the second problem, recall would be the best measurement to make sure they are not giving out 
#recalls to people who don't have an defective duck

confusion_matrix(accuracy.actual, accuracy.model1)


array([[  8,   8],
       [  2, 182]])

In [11]:
182 / (8 + 182) # model 1 recall 96%

0.9578947368421052

In [12]:
confusion_matrix(accuracy.actual, accuracy.model2)

array([[  9,   7],
       [ 81, 103]])

In [13]:
#model 2 recall 92%
103/ (9 + 103) 

0.9196428571428571

In [14]:
confusion_matrix(accuracy.actual, accuracy.model3)

array([[13,  3],
       [86, 98]])

In [15]:
98/ (13 + 98) #Recall is 88%

0.8828828828828829

#### therefore, model 1 would be the best at ensuring that no defective ducks are accidently labled as 

### Question 4

In [16]:
paws  = pd.read_csv('gives_you_paws.csv')

In [17]:
paws

actual model1 model2 model3 model4
0       cat    cat    dog    cat    dog
1       dog    dog    cat    cat    dog
2       dog    cat    cat    cat    dog
3       dog    dog    dog    cat    dog
4       cat    cat    cat    dog    dog
...     ...    ...    ...    ...    ...
4995    dog    dog    dog    dog    dog
4996    dog    dog    cat    cat    dog
4997    dog    cat    cat    dog    dog
4998    cat    cat    cat    cat    dog
4999    dog    dog    dog    dog    dog

[5000 rows x 5 columns]

In [18]:
paws["baseline_prediction"] = 'dog'

In [19]:
paws

actual model1 model2 model3 model4 baseline_prediction
0       cat    cat    dog    cat    dog                 dog
1       dog    dog    cat    cat    dog                 dog
2       dog    cat    cat    cat    dog                 dog
3       dog    dog    dog    cat    dog                 dog
4       cat    cat    cat    dog    dog                 dog
...     ...    ...    ...    ...    ...                 ...
4995    dog    dog    dog    dog    dog                 dog
4996    dog    dog    cat    cat    dog                 dog
4997    dog    cat    cat    dog    dog                 dog
4998    cat    cat    cat    cat    dog                 dog
4999    dog    dog    dog    dog    dog                 dog

[5000 rows x 6 columns]

In [31]:
confusion_matrix(paws.actual, paws.model1)

array([[1423,  323],
       [ 640, 2614]])

In [20]:
model_accuracy1 = (paws.model1 == paws.actual).mean()
baseline_accuracy1 = (paws.baseline_prediction == paws.actual).mean()

print(f'   model accuracy1: {model_accuracy1:.2%}')
print(f'baseline accuracy1: {baseline_accuracy1:.2%}')
print('\n')

model_accuracy2 = (paws.model2 == paws.actual).mean()
baseline_accuracy2 = (paws.baseline_prediction == paws.actual).mean()

print(f'   model accuracy2: {model_accuracy2:.2%}')
print(f'baseline accuracy2: {baseline_accuracy2:.2%}')
print('\n')


model_accuracy3 = (paws.model3 == paws.actual).mean()
baseline_accuracy3 = (paws.baseline_prediction == paws.actual).mean()

print(f'   model accuracy3: {model_accuracy3:.2%}')
print(f'baseline accuracy3: {baseline_accuracy3:.2%}')

print('\n')

model_accuracy4 = (paws.model4 == paws.actual).mean()
baseline_accuracy4 = (paws.baseline_prediction == paws.actual).mean()

print(f'   model accuracy4: {model_accuracy4:.2%}')
print(f'baseline accuracy4: {baseline_accuracy4:.2%}')



   model accuracy1: 80.74%
baseline accuracy1: 65.08%


   model accuracy2: 63.04%
baseline accuracy2: 65.08%


   model accuracy3: 50.96%
baseline accuracy3: 65.08%


   model accuracy4: 74.26%
baseline accuracy4: 65.08%


above you can see how the different models compare to the baseline. model 1 and 4 appear to have greater accuracy than the baseline.

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(paws.actual, paws.model1, normalize=True))
print(accuracy_score(paws.actual, paws.model2, normalize=True))
print(accuracy_score(paws.actual, paws.model3, normalize=True))
print(accuracy_score(paws.actual, paws.model4, normalize=True))

0.8074
0.6304
0.5096
0.7426


In [45]:
from sklearn.metrics import precision_score
print(precision_score(paws.actual, paws.model1, pos_label = 'dog', average = 'binary'))
print(precision_score(paws.actual, paws.model2, pos_label = 'dog', average = 'binary'))
print(precision_score(paws.actual, paws.model3, pos_label = 'dog', average = 'binary'))
print(precision_score(paws.actual, paws.model4, pos_label = 'dog', average = 'binary'))

0.8900238338440586
0.8931767337807607
0.6598883572567783
0.7312485304490948


In [46]:
from sklearn.metrics import recall_score
print(recall_score(paws.actual, paws.model1, pos_label = 'dog', average = 'binary'))
print(recall_score(paws.actual, paws.model2, pos_label = 'dog', average = 'binary'))
print(recall_score(paws.actual, paws.model3, pos_label = 'dog', average = 'binary'))
print(recall_score(paws.actual, paws.model4, pos_label = 'dog', average = 'binary'))


0.803318992009834
0.49078057775046097
0.5086047940995697
0.9557467732022127


In [53]:
from sklearn.metrics import classification_report
classification_report(paws.actual, paws.model1, output_dict = True)

{'cat': {'precision': 0.6897721764420747,
  'recall': 0.8150057273768614,
  'f1-score': 0.7471777369388292,
  'support': 1746},
 'dog': {'precision': 0.8900238338440586,
  'recall': 0.803318992009834,
  'f1-score': 0.8444516233241802,
  'support': 3254},
 'accuracy': 0.8074,
 'macro avg': {'precision': 0.7898980051430666,
  'recall': 0.8091623596933477,
  'f1-score': 0.7958146801315047,
  'support': 5000},
 'weighted avg': {'precision': 0.8200959550792857,
  'recall': 0.8074,
  'f1-score': 0.8104835821984157,
  'support': 5000}}